# Generated by Django 4.0.1 on 2022-01-18 22:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtag',
            name='created',
        ),
        migrations.RemoveField(
            model_name='hashtag',
            name='tweets',
        ),
        migrations.RemoveField(
            model_name='hashtag',
            name='updated',
        ),
        migrations.AddField(
            model_name='tweet',
            name='hashtag',
            field=models.ManyToManyField(related_name='tweets_under_hashtag', to='app.HashTag'),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='followingTweets',
            field=models.ManyToManyField(related_name='followed_tweets', to='app.HashTag'),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='followingUsers',
            field=models.ManyToManyField(related_name='followed_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
