# Generated by Django 4.0.1 on 2022-01-19 00:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_remove_hashtag_created_remove_hashtag_tweets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='followingTweets',
            field=models.ManyToManyField(blank=True, related_name='followed_tweets', to='app.HashTag'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='followingUsers',
            field=models.ManyToManyField(blank=True, related_name='followed_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
